#!/bin/bash

set -ex

mkdir -p repo
rm -rvf repo/* 
rm -rf repo/.??* 
rm -rvf repoMachine2/*
rm -rf repoMachine2/.??*


DATADIR="$(pwd)/data"
export PATH="$(pwd)/../blib/script:$(pwd)/../bin:$PATH"
export PERL5LIB="$(pwd)/../blib/lib:$(pwd)/../lib:$PATH"

# check that options are correctly connected to config variables
git-labbook help

mkdir -p repo
cd repo

git init
git am $DATADIR/000[1234]-*

git-labbook init

git-labbook xp start xp1 --branch xp1 --no-labbook-entry
git am $DATADIR/000[56]-*

git checkout master
git am $DATADIR/000[78]-*

git checkout xp1
git am $DATADIR/000[9]-*

git checkout data
git am $DATADIR/001[0]-*

git checkout xp1
git-labbook xp finish

git checkout master
git am $DATADIR/001[12345]-*

git-labbook xp start xp2
git am $DATADIR/001[6]-*

git checkout data
git am $DATADIR/001[7]-*

git checkout xp/xp2
git-labbook xp finish

git am $DATADIR/001[8]-*

git checkout master
git am $DATADIR/001[9]-*
git tag stable0.9

#############################################
# Launching xp3 experiments on another machine
cd ..

git clone -b master --single-branch repo repoMachine2 # git-labbook setup or git-labbook clone src or something similar

cd repoMachine2

git-labbook xp start xp3 -b xp3 --no-labbook-entry
git am $DATADIR/002[01234]-*
git push -u origin xp3 # git-labbook xp push

cd ..
cd repo

git checkout xp3
git-labbook xp finish
#git checkout data # no need for this one, as it is already done with git-labbook xp finish
#../git_merge.sh -b heads/xp3 # no need for this one, as it is already done with git-labbook xp finish
git am $DATADIR/002[5]-*
#############################################

git checkout master
git am $DATADIR/002[6]-*

echo "SUCCESS REBUILD"
